// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class UpdateColumnsInTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "TemplateName",
                table: "InvoiceTemplates",
                newName: "Name");

            migrationBuilder.RenameColumn(
                name: "TemplateData",
                table: "InvoiceTemplates",
                newName: "Data");

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "InvoiceTemplates",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "InvoiceTemplateName",
                table: "BatchInvoices",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "InvoiceTemplates");

            migrationBuilder.DropColumn(
                name: "InvoiceTemplateName",
                table: "BatchInvoices");

            migrationBuilder.RenameColumn(
                name: "Name",
                table: "InvoiceTemplates",
                newName: "TemplateName");

            migrationBuilder.RenameColumn(
                name: "Data",
                table: "InvoiceTemplates",
                newName: "TemplateData");
        }
    }
}
