// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class AddForeignKeysToTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "UserBankDataId",
                table: "BatchInvoices",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "UserDetailId",
                table: "BatchInvoices",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<Guid>(
                name: "UserId",
                table: "BatchInvoices",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoices_UserBankDataId",
                table: "BatchInvoices",
                column: "UserBankDataId");

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoices_UserDetailId",
                table: "BatchInvoices",
                column: "UserDetailId");

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoices_UserId",
                table: "BatchInvoices",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_BatchInvoices_UserBankData",
                table: "BatchInvoices",
                column: "UserBankDataId",
                principalTable: "UserBankData",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_BatchInvoices_UserDetails",
                table: "BatchInvoices",
                column: "UserDetailId",
                principalTable: "UserDetails",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_BatchInvoices_Users",
                table: "BatchInvoices",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BatchInvoices_UserBankData",
                table: "BatchInvoices");

            migrationBuilder.DropForeignKey(
                name: "FK_BatchInvoices_UserDetails",
                table: "BatchInvoices");

            migrationBuilder.DropForeignKey(
                name: "FK_BatchInvoices_Users",
                table: "BatchInvoices");

            migrationBuilder.DropIndex(
                name: "IX_BatchInvoices_UserBankDataId",
                table: "BatchInvoices");

            migrationBuilder.DropIndex(
                name: "IX_BatchInvoices_UserDetailId",
                table: "BatchInvoices");

            migrationBuilder.DropIndex(
                name: "IX_BatchInvoices_UserId",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "UserBankDataId",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "UserDetailId",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "BatchInvoices");
        }
    }
}
