// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class ChangeBatchInvoicesColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AdditionalText",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "Amount",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "CurrencyAmount",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "CurrencyCode",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "CustomerGroup",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "Name",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "OpenAmount",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "OpenCurrencyAmount",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "PersonResponsible",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "SalesResponsible",
                table: "BatchInvoices");

            migrationBuilder.RenameColumn(
                name: "Text",
                table: "BatchInvoices",
                newName: "CompanyName");

            migrationBuilder.RenameColumn(
                name: "PaymentStatus",
                table: "BatchInvoices",
                newName: "PaymentType");

            migrationBuilder.AddColumn<string>(
                name: "CompanyVatNumber",
                table: "BatchInvoices",
                type: "nvarchar(25)",
                maxLength: 25,
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "CompanyVatNumber",
                table: "BatchInvoices");

            migrationBuilder.RenameColumn(
                name: "PaymentType",
                table: "BatchInvoices",
                newName: "PaymentStatus");

            migrationBuilder.RenameColumn(
                name: "CompanyName",
                table: "BatchInvoices",
                newName: "Text");

            migrationBuilder.AddColumn<string>(
                name: "AdditionalText",
                table: "BatchInvoices",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "Amount",
                table: "BatchInvoices",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "CurrencyAmount",
                table: "BatchInvoices",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "CurrencyCode",
                table: "BatchInvoices",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "CustomerGroup",
                table: "BatchInvoices",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "BatchInvoices",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<decimal>(
                name: "OpenAmount",
                table: "BatchInvoices",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "OpenCurrencyAmount",
                table: "BatchInvoices",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "PersonResponsible",
                table: "BatchInvoices",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SalesResponsible",
                table: "BatchInvoices",
                type: "nvarchar(255)",
                maxLength: 255,
                nullable: true);
        }
    }
}
