// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class AddBatchInvoicesProcessingTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BatchInvoicesProcessing",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ProcessBatchKey = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    BatchProcessingTime = table.Column<TimeSpan>(type: "time", nullable: true),
                    Status = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BatchInvoicesProcessing", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BatchInvoicesProcessing_BatchInvoices",
                        column: x => x.ProcessBatchKey,
                        principalTable: "BatchInvoices",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoicesProcessing_ProcessBatchKey",
                table: "BatchInvoicesProcessing",
                column: "ProcessBatchKey");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BatchInvoicesProcessing");
        }
    }
}
