// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class ChangeForeignKeysAssignment : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BatchInvoicesProcessing_BatchInvoices",
                table: "BatchInvoicesProcessing");

            migrationBuilder.DropIndex(
                name: "IX_BatchInvoicesProcessing_ProcessBatchKey",
                table: "BatchInvoicesProcessing");

            migrationBuilder.DropColumn(
                name: "ProcessBatchKey",
                table: "BatchInvoicesProcessing");

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoices_ProcessBatchKey",
                table: "BatchInvoices",
                column: "ProcessBatchKey");

            migrationBuilder.AddForeignKey(
                name: "FK_BatchInvoices_BatchInvoicesProcessing",
                table: "BatchInvoices",
                column: "ProcessBatchKey",
                principalTable: "BatchInvoicesProcessing",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_BatchInvoices_BatchInvoicesProcessing",
                table: "BatchInvoices");

            migrationBuilder.DropIndex(
                name: "IX_BatchInvoices_ProcessBatchKey",
                table: "BatchInvoices");

            migrationBuilder.AddColumn<Guid>(
                name: "ProcessBatchKey",
                table: "BatchInvoicesProcessing",
                type: "uniqueidentifier",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.CreateIndex(
                name: "IX_BatchInvoicesProcessing_ProcessBatchKey",
                table: "BatchInvoicesProcessing",
                column: "ProcessBatchKey");

            migrationBuilder.AddForeignKey(
                name: "FK_BatchInvoicesProcessing_BatchInvoices",
                table: "BatchInvoicesProcessing",
                column: "ProcessBatchKey",
                principalTable: "BatchInvoices",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
