// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace InvoiceGenerator.Backend.Database.Migrations
{
    public partial class RemoveAndRenameColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AddressLine1",
                table: "BatchInvoices");

            migrationBuilder.DropColumn(
                name: "AddressLine2",
                table: "BatchInvoices");

            migrationBuilder.RenameColumn(
                name: "AddressLine3",
                table: "BatchInvoices",
                newName: "StreetAddress");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "StreetAddress",
                table: "BatchInvoices",
                newName: "AddressLine3");

            migrationBuilder.AddColumn<string>(
                name: "AddressLine1",
                table: "BatchInvoices",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "AddressLine2",
                table: "BatchInvoices",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");
        }
    }
}
