# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - invoicegenerator-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://invoicegenerator.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1524d9cfabe9457eaefac6e76ca58381 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3fb531ee914f40818d91ff80047a984a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: invoicegenerator.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1524d9cfabe9457eaefac6e76ca58381 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'invoicegenerator-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f1b7d6d01514866933e8082fb9437c5 }}
        images: 'invoicegenerator.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1524d9cfabe9457eaefac6e76ca58381 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'